version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo Building the application...
      - zip -r myapp.zip .  # Package the application into a ZIP file

artifacts:
  files:
    - myapp.zip
  discard-paths: yes
